/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId'
import { Route as ApiPublicCronAutopilotRouteImport } from './routes/api/public/cron/autopilot'
import { Route as ApiPublicFacebookCallbackRouteImport } from './routes/api/public/facebook/callback'
import { Route as ApiPublicYoutubeCallbackRouteImport } from './routes/api/public/youtube/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAutopilotRoute = ApiPublicCronAutopilotRouteImport.update({
  id: '/api/public/cron/autopilot',
  path: '/api/public/cron/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFacebookCallbackRoute =
  ApiPublicFacebookCallbackRouteImport.update({
    id: '/api/public/facebook/callback',
    path: '/api/public/facebook/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicYoutubeCallbackRoute =
  ApiPublicYoutubeCallbackRouteImport.update({
    id: '/api/public/youtube/callback',
    path: '/api/public/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/api/public/cron/autopilot': typeof ApiPublicCronAutopilotRoute
  '/api/public/facebook/callback': typeof ApiPublicFacebookCallbackRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/api/public/cron/autopilot': typeof ApiPublicCronAutopilotRoute
  '/api/public/facebook/callback': typeof ApiPublicFacebookCallbackRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channel/$channelId': typeof ChannelChannelIdRoute
  '/api/public/cron/autopilot': typeof ApiPublicCronAutopilotRoute
  '/api/public/facebook/callback': typeof ApiPublicFacebookCallbackRoute
  '/api/public/youtube/callback': typeof ApiPublicYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channel/$channelId'
    | '/api/public/cron/autopilot'
    | '/api/public/facebook/callback'
    | '/api/public/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channel/$channelId'
    | '/api/public/cron/autopilot'
    | '/api/public/facebook/callback'
    | '/api/public/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/channel/$channelId'
    | '/api/public/cron/autopilot'
    | '/api/public/facebook/callback'
    | '/api/public/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelChannelIdRoute: typeof ChannelChannelIdRoute
  ApiPublicCronAutopilotRoute: typeof ApiPublicCronAutopilotRoute
  ApiPublicFacebookCallbackRoute: typeof ApiPublicFacebookCallbackRoute
  ApiPublicYoutubeCallbackRoute: typeof ApiPublicYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/autopilot': {
      id: '/api/public/cron/autopilot'
      path: '/api/public/cron/autopilot'
      fullPath: '/api/public/cron/autopilot'
      preLoaderRoute: typeof ApiPublicCronAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/facebook/callback': {
      id: '/api/public/facebook/callback'
      path: '/api/public/facebook/callback'
      fullPath: '/api/public/facebook/callback'
      preLoaderRoute: typeof ApiPublicFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube/callback': {
      id: '/api/public/youtube/callback'
      path: '/api/public/youtube/callback'
      fullPath: '/api/public/youtube/callback'
      preLoaderRoute: typeof ApiPublicYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelChannelIdRoute: ChannelChannelIdRoute,
  ApiPublicCronAutopilotRoute: ApiPublicCronAutopilotRoute,
  ApiPublicFacebookCallbackRoute: ApiPublicFacebookCallbackRoute,
  ApiPublicYoutubeCallbackRoute: ApiPublicYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
